language: ruby

rvm:
 - 2.2
 - 2.3
 - 2.4

env:
  - BUNDLE_PATH=vendor/bundle

cache: bundler

install:
  - bundle install --jobs=4
  - bundle exec appraisal install --jobs=4

script:
  - bundle exec appraisal rspec spec
  - bundle exec rake coveralls:push
